package com.madro.cook.models;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Recipes")
public class Recipe {

	private String id;
	private String name;
	private String type;
	private List<Ingredient> ingredients;
	
	public Recipe(String id, String name, String type) {
		super();
		this.id = id;
		this.name = name;
		this.type = type;
	}
	public Recipe(String name, String type) {
		super();
		this.name = name;
		this.type = type;
	}
	
	public Recipe() {
		super();
		// TODO Auto-generated constructor stub
	}
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	@DynamoDBAttribute
	public List<Ingredient> getIngredients() {
		return ingredients;
	}
	public void setIngredients(List<Ingredient> ingredients) {
		this.ingredients = ingredients;
	}
	
}
